# -*- coding: utf-8 -*-
"""Movie_Rating Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fGYdsiwl5V9HSzoB1SiWnOS6XUyz4pr_
"""

#Loading data
import numpy as np
import pandas as pd

df=pd.read_csv("/content/imdb_top_1000.csv")
df.head()
df.info()
df.describe()
df.isnull()

from google.colab import drive
drive.mount('/content/drive')

#inspection
df.isnull().sum()

df[["Released_Year", "Gross"]].head(10)

df["Gross"]=df["Gross"].str.replace(",","")
df["Gross"]=pd.to_numeric(df["Gross"])

df['Released_Year'].unique()

df['Released_Year'].sort_values().tail()
df['Released_Year']=df['Released_Year'].replace("PG",np.nan)

df.info()

ratings=df["IMDB_Rating"]

print("Mean Rating", np.mean(ratings))
print("Median Rating", np.median(ratings))
print("Standard Deviation", np.std(ratings))

#Genre Anaysis
genre_rating=df.groupby("Genre")["IMDB_Rating"].mean().sort_values(ascending=False)
print(genre_rating)

#Director Analysis
director_rating=df.groupby("Director")["IMDB_Rating"].mean().sort_values(ascending=False)
print(director_rating)

#Year Analysis
year_rating=df.groupby("Released_Year")["IMDB_Rating"].mean().sort_index()
print(year_rating)

#Data Visualizations
import matplotlib.pyplot as plt

#Avg rating by genre
plt.figure(figsize=(10,5))
Avg_IMDB_Rating=np.mean(ratings)
plt.bar(
    genre_rating.index,
    genre_rating.values

)
plt.title("Average Movie Rating by Genre")
plt.xlabel("Genre")
plt.ylabel("Avg_IMDB_Rating")
plt.show()

avg_IMDB_Rating=np.mean(ratings)
print(avg_IMDB_Rating)

genre_rating = (
    df.groupby("Genre")["IMDB_Rating"]
    .mean()
    .sort_values(ascending=False)
)

# Take top 10 for readability
top_genres = genre_rating.head(10)

plt.figure(figsize=(10,5))

plt.bar(
    top_genres.index,
    top_genres.values,
    color="green"
)

plt.title("Top Genres by Average IMDb Rating")
plt.xlabel("Genre")
plt.ylabel("Average IMDb Rating")

plt.xticks(rotation=45)

plt.show()

director_rating = (
    df.groupby("Director")["IMDB_Rating"]
    .mean()
    .sort_values(ascending=False)
)

top_directors = director_rating.head(10)


plt.figure(figsize=(10,5))

plt.bar(
    top_directors.index,
    top_directors.values,
    color="purple"
)

plt.title("Top Directors by Average IMDb Rating")
plt.xlabel("Director")
plt.ylabel("Average IMDb Rating")

plt.xticks(rotation=45)

plt.show()

year_rating = (
    df.groupby("Released_Year")["IMDB_Rating"]
    .mean()
    .sort_index()
)

top_10_years = year_rating.head(20)

plt.figure(figsize=(12,5))

plt.plot(
    top_10_years.index,
    top_10_years.values,
    marker="o",
    color="blue"
)

plt.title("Average IMDb Rating Trend Over Years")
plt.xlabel("Year")
plt.ylabel("Average IMDb Rating")

plt.grid(True)

plt.show()

gross_df = df.dropna(subset=["Gross"])


plt.figure(figsize=(8,5))

plt.scatter(
    gross_df["Gross"],
    gross_df["IMDB_Rating"],
    alpha=0.5,
    color="red"
)

plt.title("Gross Revenue vs IMDb Rating")
plt.xlabel("Gross Revenue")
plt.ylabel("IMDb Rating")

plt.show()

top_movies = (
    df[["Series_Title","IMDB_Rating"]]
    .sort_values(
        by="IMDB_Rating",
        ascending=False
    )
    .head(10)
)


plt.figure(figsize=(10,6))

plt.barh(
    top_movies["Series_Title"],
    top_movies["IMDB_Rating"],
    color="orange"
)

plt.xlabel("IMDb Rating")
plt.ylabel("Movie")

plt.title("Top 10 Rated Movies")

plt.gca().invert_yaxis()

plt.show()

#MOCK STARTED FROM HERE
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

genre_rating= df.groupby("Genre")["IMDB_Rating"].mean().head(3)

plt.plot(
    genre_rating.index,
    genre_rating.values
)
plt.xlabel("Genre")
plt.ylabel("IMDB_Rating")
plt.title("Genre wise Avg Movie Rating")
plt.show()

genre_rating = df.groupby("Genre")["IMDB_Rating"].mean().sort_values(ascending=False)

top5 = genre_rating.head(5)

plt.figure(figsize=(8,5))
plt.bar(top5.index, top5.values)
plt.xlabel("Genre")
plt.ylabel("Average Rating")
plt.title("Top 5 Genres by Average IMDb Rating")
plt.xticks(rotation=45)
plt.show()



# plt.bar(df["Genre"], df["IMDB_Rating"])
# plt.xlabel("Genre")
# plt.ylabel("Rating")
# plt.title("Genre vs Rating")
# plt.show()

genre_rating=df['Genre'].value_counts().head()
plt.pie(
    genre_rating,
    labels=genre_rating.index,
    autopct="%1.f%%"
)
plt.show()

import seaborn as sns
#heatmap
numeric_df=df.select_dtypes(include="number")
corr=numeric_df.corr()
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Heatmap")
plt.show()

yearly_analsis=df.groupby("Released_Year")['IMDB_Rating'].mean().sort_values(ascending=False).head(10)
plt.plot(
    yearly_analsis.index,
    yearly_analsis.values,
    marker="o"
)
plt.xlabel("Year")
plt.ylabel("Rating")
plt.title("Year wise rating")
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt

genre_rating=df.groupby("Genre")["IMDB_Rating"].mean().head(3)

plt.plot(
    genre_rating.index,
    genre_rating.values
)
plt.xlabel("Genre")
plt.ylabel("IMDB_Rating")
plt.show()

